### ISSUE TITLE
Latest build spamming errors

### ISSUE THREAD

**Issue by Solanis** [teelolws/DataStore_Rares#1]
Spamming errors a lot. (Latest Datastore_Conevenants also has issues; see separate report for that.)

BugSack output:
1155x DataStore_Rares\DataStore_Rares-9.0.5-018.lua:48: attempt to index local 'char' (a nil value)
[string "@DataStore_Rares\DataStore_Rares-9.0.5-018.lua"]:48: in function <DataStore_Rares\DataStore_Rares.lua:46>
[string "@DataStore_Rares\DataStore_Rares-9.0.5-018.lua"]:91: in function <DataStore_Rares\DataStore_Rares.lua:90>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/DataStore_Rares/commit/b3d0433a90c3b23e5e9da5fcce311650d294b1ac
